#!/bin/bash
#chkconfig: 345 99 99
#description:sp24-teachersubservice server
#processname:sp24-teachersubservice
case $1 in
   start) /www/jarservice/SpringClound2/sp24-teachersubservice/sp.sh;; # 开启redis的命令   
   stop) su root /www/jarservice/SpringClound2/sp24-teachersubservice/sp.sh;; # 启动杀死redis进程的脚本
   *) echo "sp24-teachersubservice start|stop" ;;         
esac 
