# application-eureka1.yml
#java -jar sp05-eureka-0.0.1-SNAPSHOT.jar --spring.profiles.active=eureka1 --server.port=2001；
#java -jar sp05-eureka-0.0.1-SNAPSHOT.jar --spring.profiles.active=eureka2 --server.port=2002；
#java -jar sp05-eureka-0.0.1-SNAPSHOT.jar --eureka.client.service-url.defaultZone=http://219.235.0.112:48011/eureka
eureka:
  instance:
    # 主机名，集群内部区分不同服务器
    hostname: eureka1
  client:
    # 单台服务器，不注册不拉取
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://219.235.0.112:48011/eureka