spring:
  application:
    name: eureka-server
  sleuth:
    sampler:
      probability: 1.0   #2.0后percentage改为probability
  zipkin:
    base-url: http://localhost:9411

server:
  port: 48011

eureka:
  instance:
    hostname: eureka1
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
